export {default as folder} from "./folder.png";
export {default as arrow} from "./arrow.png";
export {default as search} from "./search.png";
export {default as star} from "./star.png";
export {default as wheel} from "./wheel.png";
export {default as slidelogo} from "./slidelogo.png";
export {default as view } from "./view.png";
export {default as move} from "./move.png";
export {default as download} from "./download.png";
export {default as menu} from "./menu.png";
export {default as group} from "./group.png";
export {default as imgfold} from "./imgfold.png";